# See full list of available spring boot properties here: 
# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

info:
   app:
      name: audit-microservice
      description: Service to presist audit events
      version: 0.1.0
      contact:
         name: Org Name
         url: https://www.example.com
         email:

logging:
   level:
      com.dtran10.service: INFO
      
server:
    context-path: /audit-service

#Database Schema Update
#liquibase:
#   changelog: db/changelog/db.changelog-master.yaml

---

spring:
    profiles: dev

    datasource:
        url: jdbc:mysql://localhost:3306/app
        username: appuser
        password: apppassword
        driver-class-name: com.mysql.jdbc.Driver
        
---

spring:
   profiles: docker
   
   datasource:
      url: jdbc:mysql://app-db/app
      username: appuser
      password: apppassword
      driver-class-name: com.mysql.jdbc.Driver
